# Uncomment the next line to define a global platform for your project
#platform :ios, '10.0'

target 'Life Timer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Life Timer

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FirebaseUI/Google', '~> 1.0'
  pod 'Firebase/Database'

  target 'Life TimerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Life TimerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
